[workspace]
authors = ["Zain-Mrza <zzmirzazz@aol.com>"]
channels = ["conda-forge"]
name = "sam2laparoscopy"
platforms = ["win-64", "linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"
pillow = ">=12.0.0,<13"

[pypi-dependencies]
sam-2 = {path = "external/sam2", editable = true}
torch = { version = ">=2.9.0", index = "https://download.pytorch.org/whl/cu128" }
ipykernel = ">=7.1.0, <8"
pip = ">=25.3, <26"
supervision = ">=0.26.1, <0.27"
plotly = { version = ">=6.4.0, <7", extras = ["express"] }
nbformat = ">=5.10.4, <6"
